-- Seed content recovered from the original dev DB (2026-07-09): cosmetics
-- catalog, battle pass season 1 + rewards, rank season 1. Idempotent —
-- every insert is ON CONFLICT DO NOTHING, so this is a no-op on databases
-- that already have the content and a full seed on fresh ones.

INSERT INTO public.battle_pass_seasons (season_number, name, starts_at, ends_at, xp_per_tier, max_tier) VALUES (1, 'Season One: First Words', '2026-05-02 07:39:03.168792+01', '2026-07-31 07:39:03.168792+01', 100, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('theme_classic', 'board_theme', 'Classic', 'The default WordWar board.', 0, 'common', '{"bg": "#0F1115", "wrong": "#3A3D44", "correct": "#3DDC97", "misplaced": "#F4B940"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('theme_neon', 'board_theme', 'Neon Pulse', 'Saturated neon, dark mood.', 299, 'rare', '{"bg": "#08080F", "wrong": "#1B1B2A", "correct": "#00FF9C", "misplaced": "#FF4FCB"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('theme_paper', 'board_theme', 'Paperback', 'Warm cream, ink-pressed letters.', 299, 'rare', '{"bg": "#F4ECDB", "wrong": "#9C8C73", "correct": "#5C7A2B", "misplaced": "#C58A2E"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('theme_obsidian', 'board_theme', 'Obsidian', 'Pitch-black with gold highlights.', 499, 'epic', '{"bg": "#000000", "wrong": "#1A1A1A", "correct": "#D4AF37", "misplaced": "#F1A33C"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('victory_pulse', 'victory_anim', 'Pulse', 'A clean radial pulse.', 0, 'common', '{"kind": "pulse", "color": "#3DDC97"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('victory_confetti', 'victory_anim', 'Confetti Storm', 'Particles for days.', 399, 'rare', '{"kind": "confetti", "palette": ["#3DDC97", "#F4B940", "#FF4FCB"]}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('victory_lightning', 'victory_anim', 'Lightning', 'Strikes from the corners.', 799, 'epic', '{"kind": "lightning"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('avatar_default', 'avatar', 'Default', 'A simple circle.', 0, 'common', '{"color": "#6B7280", "shape": "circle"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('avatar_fox_01', 'avatar', 'Fox', 'Stylized fox.', 199, 'common', '{"asset": "fox_01"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('avatar_owl_01', 'avatar', 'Owl', 'Wide-eyed and ready.', 199, 'common', '{"asset": "owl_01"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('nameplate_plain', 'nameplate', 'Plain', 'No effects.', 0, 'common', '{"effect": "none"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('nameplate_gold', 'nameplate', 'Gold', 'Solid gold name.', 299, 'rare', '{"color": "#D4AF37", "effect": "solid"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('nameplate_rainbow', 'nameplate', 'Spectrum', 'Animated rainbow shimmer.', 599, 'epic', '{"effect": "gradient_shimmer"}', true, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('border_bronze', 'profile_border', 'Bronze Frame', 'Earned: hit Bronze.', 0, 'common', '{"color": "#A97142"}', false, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('border_diamond', 'profile_border', 'Diamond Frame', 'Earned: hit Diamond.', 0, 'epic', '{"color": "#7CC8FF"}', false, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.cosmetics (id, category, name, description, price_cents, rarity, render_data, available_in_shop, created_at) VALUES ('border_legend', 'profile_border', 'Legend Frame', 'Top 500 of a season.', 0, 'legendary', '{"glow": true, "color": "#FFD700"}', false, '2026-05-09 07:39:03.162117+01') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 5, 'free', 'theme_paper') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 10, 'free', 'avatar_fox_01') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 15, 'free', 'victory_pulse') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 25, 'free', 'nameplate_plain') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 50, 'free', 'theme_neon') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 1, 'premium', 'theme_obsidian') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 5, 'premium', 'avatar_owl_01') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 10, 'premium', 'nameplate_gold') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 20, 'premium', 'victory_confetti') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 30, 'premium', 'victory_lightning') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 40, 'premium', 'nameplate_rainbow') ON CONFLICT DO NOTHING;
INSERT INTO public.battle_pass_rewards (season_number, tier, track, cosmetic_id) VALUES (1, 50, 'premium', 'border_legend') ON CONFLICT DO NOTHING;
INSERT INTO public.rank_seasons (id, name, starts_at, ends_at, soft_reset_delta, created_at) VALUES (1, 'Season 1', '2026-05-15 18:15:13.841891+01', '2026-07-10 18:15:13.841891+01', 200, '2026-05-15 18:15:13.841891+01') ON CONFLICT DO NOTHING;
SELECT pg_catalog.setval('public.rank_seasons_id_seq', 1, true);
