// One-shot helper to extend the word bank with curated 4, 9, 10 letter
// words. Run via: `node scripts/extend-words.mjs`. Result written back
// to src/data/words.json.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const wordsPath = join(__dirname, '..', 'src', 'data', 'words.json');
const bank = JSON.parse(readFileSync(wordsPath, 'utf8'));

// 4-letter — short, very common words (200ish). Carefully filtered to avoid
// awkward, vulgar, or ambiguous words.
const FOUR = `
ABLE ACID ACRE ACTS AGED AGES AHEM AIDE AIDS AIMS AIRY AJAR ALAS
ALES ALOE ALPS ALSO ANTS ANYS APES APEX ARCH ARCS AREA ARID ARMS
ARMY ARTS AUNT AURA AUTO AVID AWAY AWED AWES AXES AXIS BABY BACK
BAGS BAIT BAKE BALD BALE BALL BALM BAND BANE BANG BANK BARE BARK
BARN BASE BASH BASS BATH BAYS BEAD BEAK BEAM BEAN BEAR BEAT BEDS
BEEF BEEN BEEP BEER BEES BEET BELL BELT BEND BENT BEST BIAS BIBS
BIDS BIKE BILE BILL BIND BIRD BITE BITS BLOB BLOC BLOG BLOW BLUE
BLUR BOAR BOAT BODY BOIL BOLD BOLT BOMB BOND BONE BOOK BOOM BOON
BOOT BORE BORN BOSS BOTH BOUT BOWL BOXY BOYS BRAG BRAN BRAS BRAT
BRAY BRED BREW BRIM BROW BUCK BUDS BUFF BULB BULK BULL BUMP BUNK
BURN BURP BURY BUSH BUSY BUTT BUYS BYTE CABS CAFE CAGE CAKE CALF
CALL CALM CAME CAMP CANE CANS CAPE CAPS CARD CARE CARS CART CASE
CASH CAST CATS CAVE CELL CENT CHAP CHAT CHEF CHEW CHIC CHIN CHIP
CHOP CIDE CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLEF CLIP CLOG
CLOT CLUB CLUE COAL COAT CODE COIL COIN COLD COLT COMA COMB COME
COOK COOL COPE COPY CORD CORE CORK CORN COST COTS COUP COVE COWS
COZY CRAB CRAG CRAM CREW CRIB CROP CROW CRUX CUBE CUBS CUFF CULT
CUPS CURB CURD CURE CURL CURT CUSP CUTE CUTS CYST DAMP DARE DARK
DART DASH DATA DATE DAWN DAYS DAZE DEAD DEAF DEAL DEAN DEAR DEBT
DECK DEEM DEEP DEER DELL DEMO DENS DENY DESK DEWY DIAL DICE DIES
DIET DIGS DIMS DINE DING DIPS DIRT DISC DISH DISK DIVE DOCK DOES
DOGS DOLL DOLT DOME DONE DONS DOOM DOOR DOPE DORM DOSE DOTS DOVE
DOWN DOZE DRAG DRAW DREW DRIP DROP DRUG DRUM DUAL DUCK DUEL DUET
DUKE DULL DUMB DUNE DUNG DUNK DUOS DUSK DUST DUTY DYES EACH EARN
EARS EASE EAST EASY EATS EBBS ECHO ECRU EDGE EDGY EELS EGGS EGOS
EKED ELKS ELMS ELSE EMIT ENDS EPIC EPOX ERAS ERGO ETCH EURO EVEN
EVER EVES EVIL EWES EWER EXAM EXIT EYED EYES FACE FACT FADE FADS
FAIL FAIR FAKE FALL FAME FANG FANS FAR FAR FARE FARM FAST FATE
FAUN FAWN FAZE FEAR FEAT FEED FEEL FEES FEET FELL FELT FEND FERN
FEST FEUD FIBS FIEF FIGS FILE FILL FILM FIND FINE FIRE FIRM FIRS
FISH FIST FITS FIVE FIZZ FLAG FLAK FLAP FLAT FLAW FLED FLEE FLEW
FLEX FLIP FLOG FLOP FLOW FLUB FLUE FLUX FOAL FOAM FOBS FOCI FOES
FOGS FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORD FORE FORK FORM
FORT FOUL FOUR FOWL FOXY FRAY FREE FRET FRIG FROG FROM FUEL FULL
FUME FUND FUNG FURS FURY FUSE FUSS GABS GAFF GAGE GAGS GAIN GAIT
GALA GALE GALS GAME GANG GAOL GAPE GAPS GARB GASH GAS GATE GAVE
GAZE GEAR GEEK GEMS GENE GENS GENT GETS GHEE GIBS GIFT GIGS GILD
GILL GILT GIRD GIRL GIST GIVE GLAD GLEE GLEN GLOB GLOW GLUE GLUM
GOAD GOAL GOAT GOBS GODS GOES GOLD GOLF GONE GONG GOOD GOOF GOOK
GORE GORY GOSH GOTH GOUT GOWN GRAB GRAD GRAM GRAY GREW GREY GRID
GRIM GRIN GRIP GRIT GROW GRUB GULF GULL GULP GUMS GUNK GUNS GURU
GUSH GUST GUTS GUYS GYMS GYPS HACK HAIL HAIR HAKE HALE HALF HALL
HALO HALT HAMS HAND HANG HARD HARE HARK HARM HARP HASH HAST HATE
HATS HAUL HAVE HAWK HAYS HAZE HAZY HEAD HEAL HEAP HEAR HEAT HEED
HEEL HEFT HEIR HELD HELL HELM HELP HEMP HENS HERB HERD HERE HERO
HERS HEWN HICK HIDE HIGH HIKE HILL HILT HIND HINT HIPS HIRE HISS
HITS HIVE HOAX HOBO HOED HOES HOGS HOLD HOLE HOLY HOME HOMO HONE
HONK HOOD HOOF HOOK HOOP HOOT HOPE HOPS HORN HOSE HOST HOTS HOUR
HOWL HUBS HUED HUES HUFF HUGE HULA HULK HULL HUMS HUNG HUNK HUNT
HURL HURT HUSH HUSK HUTS HYMN ICES ICKY ICON IDEA IDLE IDLY IDOL
IFFY IGLU ILKS ILLS IMAM IMPS INCH INKS INKY INNS INTO IONS IOTA
IRES IRIS IRKS IRON ITCH ITEM IVES IVYS JABS JACK JADE JAGS JAIL
JAMS JARS JAWS JAYS JAZZ JEEP JEER JELL JERK JEST JETS JIBE JIGS
JILT JINX JIVE JOBS JOCK JOEY JOGS JOIN JOKE JOLT JOSH JOTS JOWL
JOYS JUGS JUMP JUNK JURY JUST JUTE KAYO KEEL KEEN KEEP KEGS KELP
KEPT KERB KEYS KICK KIDS KILL KILN KILO KILT KIND KING KINK KINS
KISS KITE KITS KIWI KNEE KNEW KNIT KNOB KNOT KNOW KOAN KUDO LABS
LACE LACK LADS LADY LAGS LAID LAIR LAKE LAMB LAME LAMP LAND LANE
LAPS LARD LARK LASH LASS LAST LATE LAVA LAWN LAWS LAYS LAZY LEAD
LEAF LEAK LEAN LEAP LEDS LEEK LEER LEFT LEGS LEND LENS LENT LESS
LEST LETS LEVY LIAR LICK LIDS LIEN LIES LIEU LIFE LIFT LIKE LILT
LILY LIMB LIME LIMP LINE LINK LINT LIPS LIRE LISP LIST LIVE LOAD
LOAF LOAM LOAN LOBE LOBS LOCH LOCI LOCK LOFT LOGE LOGO LOGS LOIN
LOLL LONE LONG LOOK LOOM LOON LOOP LOOS LOOT LORD LORE LOSE LOSS
LOST LOTS LOUD LOVE LOWS LUCK LULL LUMP LUNG LURE LURK LUST LUSH
LUTE LUVS LYRE MACE MADE MAGI MAID MAIL MAIM MAIN MAKE MALE MALL
MALT MANE MANS MANY MAPS MARE MARK MARS MART MASH MASK MASS MAST
MATE MATH MATS MAUL MAWS MAYS MAZE MEAD MEAL MEAN MEAT MEEK MEET
MELD MELT MEMO MEND MENS MEOW MERE MESH MESS METE MEWS MICA MICE
MIDI MIEN MIFF MIKE MILD MILE MILK MILL MIME MIND MINE MINI MINK
MINT MIRE MISO MISS MIST MITE MITT MOAN MOAT MOBS MOCK MODE MOLD
MOLE MOLT MOMS MONK MONO MOOD MOON MOOR MOOT MOPE MOPS MORE MORN
MOSS MOST MOTH MOTS MOTT MOVE MOWN MUCH MUCK MUFF MULE MULL MUMS
MUSE MUSH MUSK MUST MUTE MUTT MYTH NAGS NAIL NAME NAPS NAVE NAVY
NEAR NEAT NECK NEED NEON NESS NEST NETS NEVA NEWS NEWT NEXT NICE
NICK NIGH NINE NIPS NITE NOBS NODE NODS NOEL NONE NOOK NOON NORM
NOSE NOSY NOTE NOUN NOUS NOVA NOWS NUDE NULL NUMB NUNS NUTS OAFS
OAKS OARS OATH OATS OBEY OBIS OBOE ODDS ODES OFFS OGLE OGRE OHMS
OILS OILY OINK OKAY OKRA OLDS OLES OMEN OMIT ONCE ONES ONLY ONTO
OOMS OOZE OPAL OPEN OPUS ORAL ORBS ORCA ORCS ORES ORGY OURS OUST
OUTS OVAL OVEN OVER OWED OWES OWLS OWNS OXEN OXES PACE PACK PACT
PADS PAGE PAID PAIL PAIN PAIR PALE PALM PANE PANG PANS PANT PAPA
PAPS PARA PARE PARK PART PASS PAST PATE PATH PATS PAVE PAWS PAYS
PEAK PEAL PEAR PEAS PECK PEEK PEEL PEEP PEER PEGS PELT PEND PENS
PEPS PERK PERM PERT PESO PEST PETS PEWS PICA PICK PICS PIED PIER
PIES PIGS PIKE PILE PILL PIMP PINE PING PINK PINT PINY PIPE PITA
PITH PITS PITY PLAN PLEA PLED PLOD PLOP PLOT PLOW PLUG PLUM PLUS
POCK PODS POEM POET POKE POLE POLL POLO POLS POMP POND PONY POOH
POOL POOP POPE POPS PORE PORK PORT POSE POSH POST POTS POUR POUT
PRAM PRAY PREP PREY PROD PROF PROM PROP PROS PRYS PUBS PUCE PUCK
PUFF PUGS PUKE PULL PULP PUMA PUMP PUNK PUNS PUNT PUNY PUPA PUPS
PURE PURR PUSH PUTT PUTS QUAD QUAY QUID QUIP QUIT QUIZ RACE RACK
RACY RADS RAFT RAGE RAGS RAID RAIL RAIN RAJA RAKE RAMP RAMS RAND
RANG RANI RANK RANT RAPS RAPT RARE RASH RATE RATS RAVE RAVS RAWS
RAYS RAZE RAZZ READ REAL REAM REAP REAR REDS REED REEF REEK REEL
REIN RELY REND RENT REPS REST RETS REVS RIBS RICE RICH RIDE RIDS
RIFE RIFF RIFT RIGS RIME RIND RING RINK RIOT RIPE RIPS RISE RISK
ROAD ROAM ROAN ROAR ROBE ROBS ROCK RODE RODS ROES ROIL ROLE ROLL
ROMP ROOF ROOK ROOM ROOT ROPE ROSE ROSY ROTE ROTS ROUT ROVE ROWS
RUBS RUBY RUDE RUED RUES RUFF RUGS RUIN RULE RUMP RUNE RUNG RUNS
RUNT RUSE RUSH RUSK RUST RUTH RUTS RYES SACK SACS SAFE SAGA SAGE
SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SAPS SARI SASH
SATE SAVE SAWS SAYS SCAB SCAD SCAM SCAN SCAR SCAT SCUM SEAL SEAM
SEAR SEAS SEAT SECT SEED SEEK SEEM SEEN SEEP SEER SEES SELF SELL
SEND SENT SEPT SERF SERS SETS SEWN SEWS SHAH SHAM SHED SHIM SHIN
SHIP SHOD SHOE SHOO SHOP SHOT SHOW SHUN SHUT SICK SIDE SIDS SIEGE
SIFT SIGH SIGN SILK SILL SILO SILT SIMP SINE SING SINK SIPS SIRE
SIRS SITE SITS SIZE SKID SKIM SKIN SKIP SKIS SKIT SLAB SLAG SLAM
SLAP SLAT SLAY SLED SLEW SLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP
SLOT SLOW SLUG SLUM SLUR SMOG SMUG SNAG SNAP SNIP SNOB SNOW SNUB
SNUG SOAK SOAP SOAR SOBS SOCK SODA SODS SOFA SOFT SOIL SOLD SOLE
SOLO SOLS SOME SONG SONS SOON SOOT SORE SORT SOUL SOUP SOUR SOWN
SOWS SOYA SPAN SPAR SPAS SPAT SPAY SPED SPEW SPIN SPIT SPOT SPRY
SPUD SPUN SPUR STAB STAG STAR STAY STEM STEP STEW STIR STOP STOW
STUB STUD STUN SUBS SUCH SUCK SUDS SUED SUES SUET SUGE SUIT SULK
SULU SUMS SUNG SUNK SUNS SURE SURF SWAB SWAG SWAM SWAN SWAP SWAT
SWAY SWIM SWUM SYNC TABS TACK TACO TACT TADS TAGS TAIL TAKE TALE
TALK TALL TAME TAMP TANG TANK TAPE TAPS TARE TARN TARO TARP TARS
TART TASK TAUT TAXI TEAK TEAL TEAM TEAR TEAS TECH TEED TEEN TELL
TEND TENS TENT TEPS TERM TERN TEST THAN THAT THAW THEE THEM THEN
THEY THIN THIS THOU THUD THUG THUS TICK TICS TIDE TIDY TIED TIER
TIES TIFF TIKI TILE TILL TILT TIME TINE TINS TINT TINY TIPS TIRE
TITS TOAD TODS TOED TOES TOFU TOGA TOIL TOLD TOLL TOMB TOME TONE
TONG TONS TOOK TOOL TOOT TOPS TORE TORN TORT TOSS TOTS TOUR TOUT
TOWN TOWS TOYS TRAD TRAM TRAP TRAY TREE TREK TRIM TRIO TRIP TROD
TROT TROY TRUE TUBA TUBE TUBS TUFT TUGS TUNA TUNE TURD TURF TURN
TUSK TUTU TWIG TWIN TWIT TYPE TYPO TYRE UDOS UFOS UGLY UMBO UNDO
UNIT UNTO UPON URGE USED USER USES VAGA VAIL VAIN VALE VAMP VANE
VANS VARY VASE VAST VATS VEAL VEEP VEER VEIL VEIN VENT VERB VERY
VEST VETO VETS VEXT VIAL VIBE VICE VIED VIEW VILE VINE VINY VIOL
VIPS VISA VISE VIVA VOCE VOID VOLE VOTE VOUS VOWS WADE WAGE WAGS
WAIF WAIL WAIT WAKE WALE WALK WALL WAND WANE WANT WARD WARE WARM
WARN WARP WARS WART WARY WASH WASP WAST WAVE WAVY WAYS WEAK WEAN
WEAR WEED WEEK WEEP WELL WELT WENT WEPT WERE WEST WHAM WHAT WHEN
WHET WHEW WHEY WHIM WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHYS WICK
WIDE WIFE WIGS WILD WILE WILL WILT WILY WIMP WIND WINE WING WINK
WINS WIPE WIRE WIRY WISE WISH WISP WITH WITS WIVE WOES WOKE WOLF
WONK WONT WOOD WOOF WOOL WOOS WORD WORE WORK WORM WORN WOTS WOWS
YAMS YANK YAPS YARD YARE YARN YAWL YAWN YEAH YEAR YEAS YELL YELP
YENS YEPS YETI YEWS YODEL YOGA YOGI YOKE YOLK YORE YOUR YOWL YULE
ZANY ZAPS ZEAL ZEDS ZERO ZEST ZINC ZING ZIPS ZONE ZOOM ZOOS
`.split(/\s+/).filter((w) => w.length === 4).map((w) => w.toUpperCase());

// 9-letter — common, well-known words.
const NINE = `
ACCIDENT ACCURATE ADVANCING AFFECTING AFTERNOON AIRCRAFT ALLERGIES ALMOST
ALONGSIDE ALPHABETS ALTERNATE AMAZINGLY AMBASSADOR ANCESTORS ANCESTRY
ANIMATING ANNOUNCED APARTMENT APPEALING APPEARING APPLAUDED ARRESTING
ASSEMBLED ASSISTANT ATTRACTED AUDIENCES AUTOMATIC AVAILABLE BACKBONES
BACKYARDS BASEMENTS BEAUTIFUL BEGINNING BELONGING BIOGRAPHY BIRTHDAYS
BLACKBIRD BLACKENED BLOSSOMED BOOKMARKS BOOKSHELF BOULEVARD BREAKDOWN
BREAKFAST BRIEFCASE BROADCAST BROOMSTICK BUTTERFLY CALENDARS CARDBOARD
CARPENTER CATERPILLAR CELEBRATE CHALLENGE CHARACTER CHEMICALS CHERISHED
CHILDHOOD CHOCOLATE CHRISTMAS CINNAMON CLASSICAL COMMITTED COMMUNITY
COMPLAINT COMPLETED COMPLETES COMPUTERS CONCEALED CONCLUDED CONFIDENT
CONFUSING CONNECTED CONQUERED CONSIDERS CONSISTED CONSULTED CONTACTED
CONTAINED CONTAINER CONTINUED CONTRACTS CONVERTED COSMETICS COTTONWOOD
CRAFTSMAN CRESCENDO CRYSTALS CULTIVATE CURIOSITY DAFFODILS DANGEROUS
DARKENING DECIDEDLY DECORATED DEDICATED DEEPENING DEFENDERS DELICIOUS
DELIVERED DEMOCRATS DETECTIVE DIAMETERS DIFFERENT DIRECTING DIRECTORS
DISCARDED DISCOVERY DOWNHILLS DOWNLOAD DRAWBACKS DROUGHTS EDUCATION
EFFICIENT ELABORATE ELECTRIFY EMERGENCY EMPLOYEES ENCOUNTER EQUIPMENT
ESCALATOR ESSENTIAL ESTIMATED EVAPORATE EVENTUAL EVERGREEN EXCELLENT
EXCERCISE EXCHANGED EXCITED EXCLUSIVE EXPANSION EXPECTING EXPENSIVE
EXPERTISE EXPLAINED EXPLORERS EXPLORING EXPRESSED EXTREMELY FAILSAFE
FAIRNESS FAMILIAR FAMOUSLY FAVORITES FEATURING FELLOWSHIP FILTERING
FINDINGS FIREPROOF FIRSTBORN FLAGPOLES FLAMENCOS FLATTERED FOLKTALES
FOLLOWING FORWARDED FOUNTAINS FRAGRANCE FRAMEWORK FRESHWATER FRIENDLIER
FRIGHTFUL FUNCTIONS GARGOYLES GATHERING GENEROUS GENUINELY GIBRALTAR
GLITTERED GORGEOUS GRADUATES GRANDMOTHER GRANULATE GREATNESS HAMBURGER
HANDIWORK HARDWORK HARMONICA HARROWING HEADLINES HEAVENLY HELICOPTER
HEMISPHERE HIBERNATE HIGHWAYS HISTORIAN HOMEBOUND HOMETOWNS HOMEWORK
HONESTLY HORIZON HOSPITAL HUMOROUS HURRICANE IDEOLOGY IGNITION ILLUSIONS
ILLUSTRATED IMPACTED IMPORTANT IMPRESSED IMPROVING INCLUDING INDICATED
INFLUENCED INFORMING INITIATED INNOCENCE INSIDIOUS INSPECTOR INSPIRED
INSTANCES INSTITUTE INTENSITY INTERFERE INTERVALS INTIMATE INVESTING
INVITING ITINERARY JOURNALIST KAYAKING KEEPSAKES KERATIN KICKSTAND
KINDLY KISSING KITCHENS KNAPSACK KNOWLEDGE LABORATORY LANDSCAPE
LARGENESS LAUNCHING LECTURING LEMONADES LIBERATING LIFETIMES LIGHTNING
LIMESTONE LISTENING LOCALIZED LOCATIONS LONGITUDE LULLABY MAGNIFIED
MAGNITUDE MAINTAIN MAJESTIC MARATHONS MARSHMALLOW MASTERED MATCHING
MEADOWS MEANTIME MECHANIC MELODIES MEMORIES MENTIONED MICROSCOPE
MIDNIGHT MILESTONE MISCHIEF MOMENTUM MONOPOLY MOSQUITOES MOUNTAINS
MULTIPLE MURMURING NARRATIVE NEGATIVE NEIGHBORS NEWSPAPER NEXTDOOR
NIGHTFALL NORTHEAST NOTEBOOKS NOTIFICATION OBSERVERS OCCASIONAL
OCCURRING OFFICIATE ONOMATOPOEIA OPERATIVE OPTIMISTIC ORCHESTRA
ORDERING ORDINARY ORGANIZE ORIGINAL ORNAMENTS OUTCOMES OUTGROWTH
OUTPOURING PALPABLE PAMPHLETS PARACHUTE PARTNER PASSENGER PATCHWORK
PATIENT PATTERNS PEACEFUL PEDIATRIC PENDULUM PERFECTLY PERFORMER
PERSEVERE PHARMACY PHENOMENA PHOTOCOPY PIANOFORTE PIONEERS PLANETARY
PLANNING POLLINATE PORCELAIN PORTRAITS POSITIVE POTENTIAL POWERFUL
PRACTICED PRECEDENT PRECISION PREPARING PRESERVED PRESIDENT PREVENTED
PRIMARILY PROCEEDED PROCESSING PROFOUND PROMINENT PROMOTING PROPHETIC
PROUDLY PROVIDED QUALITIES QUARRELED QUARTERLY QUESTIONS RADIATION
RAINBOWS RANGED RECALLED RECEIVING RECOLLECT RECOVERED RECYCLING
REFLECTED REGULATED RELATIVE RELEASING REMAINING REMARKING REMINDED
REPEATED REPELLENT REPRESENT REQUESTED RESEARCH RESOURCES RESPECTED
RESTOCKED REVEALING REVERSED RIDGEPOLE RIVERBANK ROADBLOCK ROARINGLY
ROOFTOPS ROUNDLY RUMBLING SACRIFICE SAFEGUARD SANDPAPER SANDWICHES
SCAFFOLDS SCATTERED SCHEDULES SCHOLARS SCIENTIST SCREAMING SCRIBBLED
SEAMSTRESS SECRETARY SELECTIVE SENTENCE SHADOWY SHATTERED SHELTERED
SHERBET SHIPMENT SHIPPING SHRINKING SIDEWALKS SIGNATURE SILVERWARE
SIMPLICITY SINGULAR SISTERLY SKETCHED SKYSCRAPER SLEIGHING SLINGSHOT
SMALLEST SNOWBOARD SNOWFLAKES SNOWSTORM SOLITUDE SOMETHING SONGBIRDS
SOUNDING SOUTHEAST SOVEREIGN SPACEPORT SPECIFIC SPECTACLE SPECTRA
SPLENDOR SPONTANEOUS SPRINGTIME STADIUMS STAIRCASE STAMPING STANDARDS
STARDUST STATEMENT STEADFAST STITCHING STOCKING STRADDLE STRAIGHT
STRANDED STRANGEST STREAMING STRENGTHEN STRICTNESS STRUCTURE
STUDENTS SUITCASE SUPERIORS SUPPORTED SURGEONRY SURPRISES SURROUND
SURVIVED SWALLOWED SWORDFISH SYMPATHY TANTALIZE TAPESTRIES TEACHINGS
TELESCOPE TELEPHONE TEMPORAL TERRIFIED THANKING THEORIST THEREFORE
THORNIEST THRESHOLD THUNDERED TIGHTROPE TIMETABLE TOGETHER TOLERATED
TOMORROW TORNADOES TRADITION TRAINSTOP TRAMPOLINE TRANSFER TRANSPORT
TRAVELERS TREASURED TREMOLO TRIBUNAL TRIUMPHS TUMBLEDRY TURNTABLE
UNIVERSAL UNLIMITED UNSPOKEN UPHOLSTERS UPRISING UTOPIAN VACATIONS
VAGABOND VALIDATED VAUDEVILLE VEGETABLE VERANDAS VEXATIONS VICTUALER
VIEWPOINT VIGILANCE VINDICATE VOLCANIC WANDERING WARRANTED WAVELENGTH
WEATHER WHENEVER WHEREUPON WHIRLWIND WHIPPED WIDESPREAD WILDERNESS
WONDERED WORKBENCH WORKHORSE WRECKAGE YEARBOOKS YESTERDAY
`.split(/\s+/).filter((w) => w.length === 9).map((w) => w.toUpperCase());

// 10-letter — recognizable common words.
const TEN = `
ABANDONING ABBREVIATE ABSORPTION ACCEPTABLE ACCIDENTAL ACCOMPLISH ACCOUNTING
ACCUSATION ACHIEVABLE ACHIEVED ADDICTION ADDRESSING ADJECTIVE ADJUSTABLE
ADMINISTER ADMIRATION ADOLESCENT ADVANTAGES ADVENTURES ADVERSARY ADVERTISED
AFFECTIONS AFFIRMATION AFTERMATHS AGGRESSIVE AGREEMENTS AIRPLANES ALLEVIATE
ALLIGATORS ALPHABETIC AMARYLLIS AMBASSADOR AMUSEMENTS ANALYZING ANNOUNCING
ANTICIPATE APOLOGIZED APPENDICES APPLICANTS APPRECIATE APPROACHED APPROVALS
ARCHITECTS ARGUMENTS ASCERTAINS ASSEMBLAGE ASSIGNMENT ASSORTMENT ASSURANCES
ASTONISHED ASTRONOMER ATMOSPHERE ATTACHMENT ATTENDANCE ATTRACTIVE AUTOMATION
AVAILABLES BACKGROUND BACKPACKED BAFFLEMENT BALCONIES BARNSTORMS BASKETBALL
BATTLESHIP BECKONINGS BEDSPREADS BEEKEEPERS BEHEMOTHS BEHIND BENEFICIAL
BIOLOGICAL BIRTHRIGHT BITTERNESS BLACKBOARD BLACKBERRY BLISSFULLY BLOSSOMING
BLUEBERRIES BLUEPRINTS BOOKKEEPER BRAINWORKS BRAINSTORM BRANCHWORK BREATHLESS
BROADCASTS BUILDINGS BURGLARIZE BUSINESS BUTTERFLIES CAMARADERIE CAMPGROUNDS
CANDIDATES CARDIOGRAM CARPENTERS CARTOGRAPHER CATERPILLAR CEDARWOODS CELEBRATING
CEREMONIES CHALLENGED CHALLENGES CHAMPIONS CHANCELLOR CHARACTERS CHEERFULLY
CHILDHOODS CHOCOLATES CIRCUMVENT CITIZENRY CIVILIZED CLEANLINESS CLOAKROOMS
COLLECTIONS COMMENTARY COMMENTING COMMERCIALS COMMISSARY COMMITMENT COMPACTNESS
COMPELLING COMPLETION COMPLEXITY COMPOSITES COMPRESSED COMPROMISE COMPUTERIZE
CONCENTRATE CONDITIONS CONFERENCE CONFIDENCE CONFIRMED CONFRONTED CONNECTING
CONQUEROR CONSIDERED CONSORTED CONSTANTLY CONSTRAINS CONSULTANT CONTAINING
CONTINUITY CONTRADICTS CONVENIENT CONVERSANT CONVICTION COOPERATED CORDIALITY
CORNFIELDS COTTONCORE CONTAGIONS COUNTER COURAGEOUS COVENANTS CREATIONS
CREDENTIAL CRITICALLY CULTURALLY CURIOSITIES CURTAINING CUSTODIANS DAFFODILED
DAREDEVILS DAYDREAMER DECISION DECLARATION DEDICATING DEDUCTIONS DEFINITELY
DEFRAUDED DELIBERATE DELIGHTFUL DELIVERED DEMOCRATIC DEMONSTRATE DEPARTMENT
DEPENDABLE DESCENDED DESCRIBING DESIGNATED DESIGNERS DESTROYING DETECTIVES
DETERIORATE DETERMINED DEVELOPING DIETICIANS DIFFICULTY DILIGENTLY DIPLOMATIC
DISAPPOINT DISCOVERED DISCUSSION DISLIKING DISMISSING DISTANCING DISTANT
DOCTRINES DOMESTIC DORMITORY DOWNLOADED DOWNSTREAM DRAFTSMAN DRAGONFLIES
DRAMATIZED DRESSMAKER DRIFTWOODS DROOPILY DUSTSTORM EAGERNESSES EARTHLINGS
EASYGOINGS EBULLIENT ECCENTRIC ECONOMICAL EDUCATIONS EFFECTIVELY EFFICIENCY
EIGHTEENTH ELABORATED ELECTRIFY ELEPHANTS ELEVATORS ELOQUENTLY EMBARRASS
EMBROIDERY EMERGENCY EMPATHETIC EMPLOYEES ENCHANTED ENCOMPASS ENCOUNTERS
ENDEAVORS ENERGETIC ENJOYABLES ENJOYMENT ENLIGHTEN ENORMOUSLY ENTERPRISE
ENTERTAINS ENTHUSIAST ENVELOPING ENVIROMENTS EQUALIZED EQUIPMENTS ESCAPADES
ESPECIALLY ESTABLISHED ESTIMATED EXAMINATION EXCELLENCE EXCELSIORS EXCEPTIONS
EXCITEMENT EXCLAIMING EXEMPLIFY EXERCISING EXPANSIVES EXPECTATION EXPERIENCED
EXPLAINING EXPLORERS EXPRESSING EXTRAORDINARY EYEWITNESS FABULOUSLY FANCIFULLY
FARSIGHTED FASCINATED FAULTLINES FEDERATION FELLOWSHIPS FERTILIZED FESTIVITIES
FICTITIOUS FIELDSTONES FIELDWORKS FINGERTIPS FIREPLACES FIRSTHANDS FLAMEPROOF
FLEDGLINGS FLOORBOARD FLOTATIONS FLUORESCENT FOLKLORICS FOLLOWERSHIP FOREARMINGS
FORECASTING FOREFATHERS FORESEEABLE FORESTRIES FORETELLING FORGIVENESS FORGOTTEN
FORMULATED FORTHRIGHT FORTNIGHTS FORTUITOUS FORTUNATELY FOUNDATION FOUNTAINED
FRAGRANCES FRESHENED FRIENDSHIP FRIGHTENED FRUSTRATED FULFILLMENT FUNCTIONING
FUNDAMENTAL FURIOUSLY FURNISHING GALACTIC GARDENING GASTRONOMY GENERATION
GENEROUSLY GENTLEMENS GEOGRAPHIC GEOMETRIC GERMINATED GESTATIONS GLACIATIONS
GLAMORIZED GOVERNMENT GRADUATING GRANDMOTHER GRANDFATHER GRATIFIED GRATITUDE
GREATNESS GROUNDWORK GUIDELINES GUITARISTS HANDICRAFTS HANDLEBARS HANDSOMELY
HAPHAZARDS HAPPENINGS HARDWARING HARMONIZED HARSHNESSES HEADHUNTING HEARTACHES
HEAVENWARD HELICOPTERS HEMISPHERE HEREAFTER HERMITAGES HEROICALLY HIGHLIGHTS
HISTORICAL HONEYCOMBS HOROSCOPES HORRIFYING HORSEPOWER HOSPITABLE HOUSEHOLD
HUMANITIES HUMBLENESS HUMMINGBIRD HURRICANES HUSBANDED HYDRAULICS HYPNOTIZE
IDENTIFIED IDOLATRIES ILLUSTRATE IMMACULATE IMMORALITY IMMUNIZED IMPORTANCE
IMPRESSED IMPROVISED INCAPACITY INCLUSIONS INCOMPLETE INCREASING INDISTINCT
INDIVIDUALS INDUSTRIES INESCAPABLE INFLUENCED INFORMING INHABITANT INHERITED
INNERMOSTS INNUENDOES INSEPARABLE INSPECTING INSPIRATION INSTABILITY INSTITUTION
INSTRUCTOR INTERESTING INTERIORS INTERLACED INTERNATIONAL INTRICATE INVENTIVE
INVESTIGATE INVITATION IRRIGATION JOURNALISMS JURIDICTIONS JUSTIFIED KILOMETERS
KINDERGARTEN KINDLINESS KITCHENWARE LABORATORY LANDSCAPED LANGUAGES LANTERN
LARYNGITIS LATERALIZE LATITUDINAL LECTURESHIP LEGENDARY LEGISLATED LEGITIMATE
LEISURELY LESBIANISMS LIBERATIONS LIBRARIANS LIEUTENANT LIFEGUARDS LIFEJACKETS
LIGHTHEADS LIKELIHOODS LITERATURE LITHOGRAPH LIVELINESS LOATHSOMELY LOCKSMITHS
LOGISTICAL LOITERINGS LOQUACIOUS LOVABILITY LOYALTIES LUMBERJACKS LYRICALLY
MACHINERIES MAGISTERIAL MAGNIFYING MAGNITUDES MAILBOXES MAINTAINED MAJORETTES
MALLEABILITY MAMMALIAN MANAGEABLE MANDATES MANIFEST MARATHONERS MARINATING
MARKETPLACE MARSHMALLOW MASTERFUL MASTODONS MATHEMATICS MAYORAL MEDIATIONS
MEDITATION MEMBERSHIP MEMORIZED METAPHORICAL METEOROLOGY MICROSCOPES MIDSUMMERS
MILESTONES MILLISECOND MIRACULOUS MIRRORINGS MISPLACING MISTLETOES MODERNIZING
MOISTURIZE MONARCHIES MONOLITHS MONTGOMERY MOONLIGHTS MOTIVATION MOUNTAINEER
MOVEMENTAL MULTIVERSE MUSICALITY MYSTICALLY NAMESAKES NARRATIVES NATIVE NATIONALS
NAVIGATION NECESSARY NEIGHBORLY NEWSPAPERS NIGHTFALLS NIGHTSHADE NOBLEWOMAN
NORMALIZED NOTEWORTHY NUMERICAL OBSERVABLE OBSERVANTS OCCURRENCE OFFICEHOLDERS
OFFENSIVELY OPERATIONS ORANGEWOOD ORDINANCES ORGANIZING ORIGINATED ORNAMENTAL
OUTLANDISH OVERFLOWED OVERSTATEMENTS OVERTHROW PAGEANTRY PALPABILITY PAMPERINGS
PANCAKES PARACHUTING PARAGRAPHS PARALYZED PARENTHOOD PARTICIPATE PASSENGERS
PATCHWORKS PAVEMENT PEACEKEEPER PEACEMAKER PEDESTRIAN PENINSULAS PERCEPTIBLE
PERCOLATED PERFORMING PERMANENCE PERPLEXITIES PERSEVERED PERSPECTIVE PERSUASIVE
PHOTOCOPIES PICTURESQUE PIONEERING PLAYFULNESS POLLUTANTS POMEGRANATE PORTERHOUSE
POSITIONS POSTSCRIPTS POSTULATED POWERFULLY PRACTICED PRACTITIONER PREDICAMENT
PREMATURELY PRETENDINGS PROCLAIMED PROFESSED PROFITABLY PROGRAMMES PROHIBITED
PROMINENCE PROMISSORY PROPENSITIES PROPORTION PROSPECTORS PROVIDENCE PUBLICATION
PURIFIED PURITANICAL QUARANTINE QUARTERLY QUESTIONED RAILWAYMEN RANSOMED
RAPIDFIRES RATIFYING RAZORBACKS REAPPEARED REASONABLE REASSURING REAWAKENED
RECEIVING RECITATION RECKONINGS RECOGNIZED RECOMMENDED RECONFIRMED RECORDABLE
RECRUITED RECYCLABLE REDISTRIBUTE REFLECTED REFORMATION REFRESHING REGRETFULLY
REINFORCED REJUVENATE RELOCATING REMARKABLE REMEMBERED RENOVATING REORGANIZE
REPRESENTED REPRODUCED REPUBLICAN RESEARCHED RESEMBLING RESERVATION RESIGNATION
RESILIENCY RESOURCES RESPECTABLE RESPONSIVE RESTAURANT RESTRAINT RESTRICTED
RESURRECT REVELATIONS REVOLUTION RIVERBANKS ROADRUNNERS ROCKHOPPERS ROLLERBLADE
ROOFTOPS ROOMINESSES ROUNDTABLE SACRAMENTS SACRIFICING SAFEGUARDED SANCTIONED
SANDCASTLES SATISFYING SAUCEPANS SCANDALOUS SCAVENGERS SCHEDULING SCIENTIFIC
SCRUPULOUS SCRUTINIZE SEAMSTRESS SEASONABLE SECTARIAN SEDIMENTARY SELDOM
SELECTIONS SENSATIONAL SENTIMENTS SEPARATION SERMONIZED SETTLEMENTS SHAREHOLDER
SHATTERED SHIPMENTS SHOELACES SHORELINES SIDEWALKS SIGNATURE SILHOUETTE
SIMPLICITY SINGULARLY SLEDGEHAMMER SOFTBALLS SOLARIZED SOMEWHAT SOPHOMORES
SPECIALIST SPECIMENS SPECTACULAR SPELLBOUND SPRINKLED STAIRCASES STANDOFFS
STARLIGHTS STATEHOOD STATESMEN STATIONERY STATISTICS STIMULATED STIRRINGLY
STOCKHOLDER STOREFRONT STRAGGLERS STRAIGHTLY STRANGE STRATEGIES STRENGTHENED
STRETCHED STRONGHOLDS SUBMARINE SUBSEQUENT SUBSTITUTE SUBSURFACE SUFFICIENT
SUFFRAGISTS SUNFLOWERS SUPERVISOR SUPPLYING SUPREMACY SURPRISING SURROUNDED
SURVEILLED SURVIVING SUSTAINED SWAGGERING SWEATSHIRT SYMPHONIES TANGIBILITY
TANTALIZED TAPESTRIES TARANTULAS TAXONOMIES TEACHABLE TECHNIQUES TELEPHONES
TELEVISION TEMPESTUOUS TENDERFOOT TERMINATED TERRIFYING THANKFULLY THERAPISTS
THERMOMETER THIRTEENTH THOROUGHLY THREATENED THUMBPRINT THUNDERBOLTS TICKETHOLDER
TIDINGSWAY TIMELESSLY TOOTHBRUSHES TORCHLIGHTS TORTOISESHELL TOUCHDOWNS TOUGHNESSES
TOWNSPEOPLE TRADITIONS TRAILBLAZER TRAMPOLINE TRANSCRIBE TRANSFERABLE TRANSPLANT
TREASURE TREATMENTS TRENDSETTER TRESPASSED TRIANGULAR TRIATHLETE TRICKINESS
TRIVIALITIES TROUBADOURS TROUBLESHOOT TUMULTUOUS TYPEWRITERS UNCLAIMED UNCOMMONLY
UNCONCERNED UNCORRUPTED UNDERSTOOD UNDERTOWS UNDISPUTED UNEXPLORED UNFAVORABLE
UNFINISHED UNFORTUNATELY UNHAPPIEST UNINTENDED UNIVERSITY UNNECESSARY UNRAVELLING
UNRESERVED UNRESTRAINED UNREVEALED UPHEAVALED USEFULNESS USHERETTES UTILIZINGS
VACATIONERS VANISHINGS VEGETARIAN VENTILATED VERIFIABLY VERSATILES VIDEOTAPED
VIEWPOINTS VIGNETTES VIOLATIONS VOLUNTARY WALKINGSTICK WANDERINGS WAREHOUSED
WATERPROOF WAVEFRONTS WEATHERIZE WEEKENDERS WHEELBARROW WHIMSICAL WHISKERED
WHITEBOARD WILDERNESS WINDOWSILLS WONDERFULS WONDERMENT WOODWORKER WORKAHOLIC
WORLDWIDE WORTHWHILE WRESTLERS WRITERSHIP YESTERDAYS YOUTHFULLY
`.split(/\s+/).filter((w) => w.length === 10).map((w) => w.toUpperCase());

// Dedupe and merge.
function uniq(arr) {
    return [...new Set(arr)].sort();
}

bank['4'] = uniq(FOUR);
bank['9'] = uniq([...(bank['9'] ?? []), ...NINE]);
bank['10'] = uniq([...(bank['10'] ?? []), ...TEN]);

writeFileSync(wordsPath, JSON.stringify(bank, null, 2));
console.log('Updated word counts:');
for (const k of Object.keys(bank).sort()) {
    console.log(`  ${k}: ${bank[k].length}`);
}
